import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor

"""
t_weight_betty.csv is generated by collecting all weights from the SQLite databases in the elastic_net_models directory.
simu_betty
"""

# 1. Setup Paths
BASE_DIR = Path(__file__).resolve().parent
DB_DIR = BASE_DIR.parent.parent / "elastic_net_models"
DATA_DIR = BASE_DIR.parent / "data"
OUTPUT_DIR = DATA_DIR / "simu_betty"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------------
# Part 1 & 2: Data Prep & Simulation (Same as before)
# ------------------------------------------------------------------
def collect_all_weights():
    db_files = list(DB_DIR.glob("*.db"))
    all_weights = []
    print(f"Reading weights from {len(db_files)} databases...")
    for db_file in db_files:
        conn = sqlite3.connect(db_file)
        df = pd.read_sql_query("SELECT weight FROM weights", conn)
        all_weights.append(df['weight'].abs())
        conn.close()
    t_weight_df = pd.DataFrame(pd.concat(all_weights, ignore_index=True), columns=['value'])
    t_weight_df.to_csv(DATA_DIR / "t_weight_betty.csv", index=False)
    return t_weight_df

def get_weight_groups(t_weight_df):
    quant = t_weight_df['value'].quantile([0, 0.2, 0.4, 0.6, 0.8, 1.0]).values
    low = t_weight_df[t_weight_df['value'] < quant[1]]['value'].values
    med = t_weight_df[(t_weight_df['value'] > quant[2]) & (t_weight_df['value'] < quant[3])]['value'].values
    high = t_weight_df[t_weight_df['value'] > quant[4]]['value'].values
    return low, med, high

def run_single_simulation(diff_p, snp_n, maf_p, loop_n, weight_type, weight_groups):
    low_w, med_w, high_w = weight_groups
    n_diff = int(np.ceil(snp_n * diff_p))
    n_common = snp_n - n_diff
    
    results = []
    for _ in range(loop_n):
        dosage = np.random.choice([0, 1, 2], size=snp_n, p=[maf_p**2, 2*maf_p*(1-maf_p), (1-maf_p)**2])
        if weight_type == "high":
            eff_w = np.random.choice(high_w, n_diff, replace=True)
            sam_w = np.random.choice(low_w, n_common, replace=True)
        elif weight_type == "med":
            eff_w = np.random.choice(med_w, n_diff, replace=True)
            sam_w = np.random.choice(low_w, n_common, replace=True)
        else: # low
            eff_w = np.random.choice(low_w, snp_n, replace=True)
            sam_w = np.array([])
        merge_weight = np.concatenate([eff_w, sam_w])
        results.append(np.sum(dosage * merge_weight))
    return results

# ------------------------------------------------------------------
# Part 3: Task Runner + Plotting Logic
# ------------------------------------------------------------------
def simulate_by_maf(args):
    """
    對應 R 的 mf_fn_mean：針對單一 MAF，產出 3x3 (Weight Type x SNP Count) 的資料
    """
    maf, snp_n_list, weight_groups = args
    diff_prop_set = np.round(np.arange(0, 0.45, 0.05), 2)
    loop_n = 500
    w_types = ["high", "med", "low"]
    
    maf_results = {}
    for snp_n in snp_n_list:
        maf_results[snp_n] = {}
        for w_type in w_types:
            all_vals = []
            for p in diff_prop_set:
                vals = run_single_simulation(p, snp_n, maf, loop_n, w_type, weight_groups)
                all_vals.extend(vals)
            
            df = pd.DataFrame({
                'diffprop': np.repeat(diff_prop_set, loop_n),
                'value': all_vals
            })
            maf_results[snp_n][w_type] = df
            
    # 執行完畢後，在這裡直接畫該 MAF 的 3x3 圖
    fig, axes = plt.subplots(3, 3, figsize=(15, 12), sharey=True)
    plt.subplots_adjust(hspace=0.3, wspace=0.3)
    
    for r_idx, w_type in enumerate(w_types):
        for c_idx, snp_n in enumerate(snp_n_list):
            ax = axes[r_idx, c_idx]
            curr_df = maf_results[snp_n][w_type]
            
            sns.ecdfplot(data=curr_df, x='value', hue='diffprop', 
                         ax=ax, palette='viridis', legend=(r_idx==0 and c_idx==1))
            
            # 設定標籤 (比照 R 的 xlab/ylab)
            row_label = w_type.capitalize()
            col_label = f"{snp_n} variants"
            
            if c_idx == 0: ax.set_ylabel(f"{row_label}\nECDF")
            if r_idx == 2: ax.set_xlabel(f"{col_label}\nGene expression")
            else: ax.set_xlabel("")
            
            ax.tick_params(axis='x', rotation=45)

    # 調整 Legend
    if axes[0, 1].get_legend():
        axes[0, 1].get_legend().set_bbox_to_anchor((0.5, 1.25))
        axes[0, 1].get_legend().set_title(None)

    plot_path = OUTPUT_DIR / f"thu_mtcars_all_{maf}_python_v2.png"
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    plt.close(fig) # 關閉圖表以節省記憶體
    
    return f"Generated 3x3 plot for MAF {maf}"

def main():
    # 1. 載入權重 (保持不變)
    if not (DATA_DIR / "t_weight_betty.csv").exists():
        t_weight_df = collect_all_weights()
    else:
        t_weight_df = pd.read_csv(DATA_DIR / "t_weight_betty.csv")
    weight_groups = get_weight_groups(t_weight_df)

    # 2. 設定參數
    maf_set = [0.95, 0.85, 0.75, 0.65, 0.55]
    snp_n_list = [1, 30, 200] # 你原本 R 腳本中間產出的圖是這三個組合
    
    tasks = [(maf, snp_n_list, weight_groups) for maf in maf_set]

    # 3. 平行執行：每個 MAF 跑一個進程，各畫一張 3x3
    print("Generating individual MAF 3x3 plots...")
    with ProcessPoolExecutor() as executor:
        results = list(executor.map(simulate_by_maf, tasks))
    
    for r in results:
        print(r)

if __name__ == "__main__":
    main()