"""
loader.py
---------
Internal data loader for PredictMP.

Reference data is read from PredictMP/data/{tissue,result_table,ks}/*.parquet,
built by code/08_build_package_data.py. Override the location with env var
PREDICTMP_DATA_DIR.
"""

import os

import pandas as pd
from pathlib import Path
from functools import lru_cache

# loader.py -> PredictMP -> PredictMP_python -> code -> PredictMP
_DATA_DIR    = Path(os.getenv("PREDICTMP_DATA_DIR",
                              Path(__file__).resolve().parents[3] / "data")).expanduser()
_TISSUE_DIR  = _DATA_DIR / "tissue"
_RT_DIR      = _DATA_DIR / "result_table"
_KS_DIR      = _DATA_DIR / "ks"

VALID_POPULATIONS = frozenset(["nfe", "eas", "afr", "ami", "amr", "asj", "fin", "mid", "sas"])


def _data_path(name: str) -> Path:
    path = _DATA_DIR / f"{name}.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"Internal data file not found: {path}\n"
            f"Run code/08_build_package_data.py to generate it."
        )
    return path


def _tissue_path(name: str) -> Path:
    path = _TISSUE_DIR / f"{name}.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"Tissue data not found: {path}\n"
            f"Run code/08_build_package_data.py to generate it."
        )
    return path


def _rt_path(name: str) -> Path:
    path = _RT_DIR / f"{name}.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"Result table not found: {path}\n"
            f"Run code/08_build_package_data.py to generate it."
        )
    return path


def _ks_path(name: str) -> Path:
    path = _KS_DIR / f"{name}.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"KS table not found: {path}\n"
            f"Run code/08_build_package_data.py to generate it."
        )
    return path


@lru_cache(maxsize=None)
def load_tissue(tissue: str, population: str = "nfe") -> pd.DataFrame:
    """
    Load the reference population predicted expression for one tissue.

    Parameters
    ----------
    tissue : str
        Tissue index string, e.g. ``"x1"`` ... ``"x49"``.
    population : str, optional
        Reference population (lowercase). One of:
        ``"nfe"``, ``"eas"``, ``"afr"``, ``"ami"``, ``"amr"``,
        ``"asj"``, ``"fin"``, ``"mid"``, ``"sas"``.
        Default is ``"nfe"``.

    Returns
    -------
    pd.DataFrame
        Columns: FID, IID, ENSG...
    """
    population = population.lower()
    if population not in VALID_POPULATIONS:
        raise ValueError(
            f"population must be one of {sorted(VALID_POPULATIONS)}, got {population!r}"
        )
    if not tissue.startswith("x") or not tissue[1:].isdigit():
        raise ValueError(f"tissue must be 'x1'...'x49', got {tissue!r}")
    return pd.read_parquet(_tissue_path(f"{population}_{tissue}"))


@lru_cache(maxsize=None)
def load_ks_table(population: str = "eas") -> pd.DataFrame | None:
    """
    Load pre-computed KS test results (population vs NFE) and mean.diff.

    Generated by 08_build_package_data.py Step 4 for every non-NFE population.
    Each row is a gene; columns are ``x{i}.ks.sig`` and ``x{i}.mean.diff``
    for each of the 49 tissues.

    Parameters
    ----------
    population : str
        Target population (lowercase). NFE returns ``None`` (no self-comparison).

    Returns
    -------
    pd.DataFrame or None
    """
    population = population.lower()
    if population == "nfe":
        return None          # NFE vs NFE comparison is meaningless
    if population not in VALID_POPULATIONS:
        raise ValueError(
            f"population must be one of {sorted(VALID_POPULATIONS)}, got {population!r}"
        )
    return pd.read_parquet(_ks_path(f"ks_{population}_nfe"))


@lru_cache(maxsize=None)
def load_result_table(population: str = "nfe") -> pd.DataFrame:
    """
    Load the result_table (SNP counts, mean, SD per gene per tissue).

    Parameters
    ----------
    population : str, optional
        Reference population (lowercase). One of:
        ``"nfe"``, ``"eas"``, ``"afr"``, ``"ami"``, ``"amr"``,
        ``"asj"``, ``"fin"``, ``"mid"``, ``"sas"``.
        Default is ``"nfe"``.

    Returns
    -------
    pd.DataFrame
        Wide table: rows = genes, columns = tissue metadata fields.
    """
    population = population.lower()
    if population not in VALID_POPULATIONS:
        raise ValueError(
            f"population must be one of {sorted(VALID_POPULATIONS)}, got {population!r}"
        )
    return pd.read_parquet(_rt_path(f"result_table_{population}"))
